version: '3.7'

networks:
  default:
    name: kong-net

services:
  kong:
    image: kong:3.1.1-alpine
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    command: "kong start"
    depends_on:
      - author-service
      - book-service
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./kong:/opt/kong

  author-service:
    build:
      context: ./author
    container_name: author-service
    hostname: author
    depends_on:
      - postgres
    
  book-service:
    build:
      context: ./book
    container_name: book-service
    hostname: book
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.4-jammy
    container_name: mongo
    hostname: book-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # volumes:
    #   - ./book_db/data:/data/db

  postgres:
    image: postgres:15.2-alpine
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=author
    volumes:
      - ./author_db/data:/var/lib/postgresql/data
      - ./author_db/init.sql:/docker-entrypoint-initdb.d/init.sql
